### ISSUE TITLE
What is pocketbase-service.exe?

### ISSUE THREAD

**Issue by GlutenBoy** [russkyc/pocketbase-service-windows#1]
Could you share the source of the pocketbase-service.exe file? I don't feel very confortable running this without seeing what it does. Thx

**Comment by russkyc** [comment]
Hi @GlutenBoy, I definitely should've added this in the readme. But that exe is the renamed winsw installer that is in this [repository](https://github.com/winsw/winsw). All the information you need and the source would be in the repository.

For transparency, you can check both md5 hashes of the exe from the winsw repository and the pocketbase-service. Or you could even use the exe from the original repo and rename it to pocketbase-service.exe and it will work the same
